# Generated by Django 4.2.1 on 2024-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmaremi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
