# Generated by Django 4.2.1 on 2024-01-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmaremi', '0002_alter_contacto_mensaje_alter_producto_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
