# Generated by Django 4.2.1 on 2024-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmaremi', '0003_alter_contacto_correo_alter_vendedor_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
