# Generated by Django 4.2.1 on 2024-01-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmaremi', '0004_producto_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendedor',
        ),
    ]
